import type { AlgoliaContentItem } from "./types";

export const MOCK_SYSTEM_LIBRARY: AlgoliaContentItem[] = [
  {
    objectID: "sys-001",
    title: "Understanding Type 2 Diabetes",
    description: "A comprehensive guide to managing type 2 diabetes including diet, exercise, and medication.",
    url: "https://www.cdc.gov/diabetes/basics/type2.html",
    category: "Diabetes",
    language: "English",
    source: "Centers for Disease Control and Prevention",
  },
  {
    objectID: "sys-002",
    title: "Asthma Overview",
    description: "Learn about asthma symptoms, triggers, and treatment options.",
    url: "https://www.cdc.gov/asthma",
    category: "Respiratory",
    language: "English",
    source: "Centers for Disease Control and Prevention",
  },
  {
    objectID: "sys-003",
    title: "Heart-Healthy Eating",
    description: "Dietary guidelines for maintaining a healthy heart and preventing cardiovascular disease.",
    url: "https://www.heart.org/en/healthy-living/healthy-eating",
    category: "Heart Health",
    language: "English",
    source: "American Heart Association",
  },
  {
    objectID: "sys-004",
    title: "Managing High Blood Pressure",
    description: "What you need to know about hypertension and how to keep it under control.",
    url: "https://www.heart.org/en/health-topics/high-blood-pressure",
    category: "Heart Health",
    language: "English",
    source: "American Heart Association",
  },
  {
    objectID: "sys-005",
    title: "Childhood Immunization Schedule",
    description: "Recommended vaccination schedule for children from birth through 18 years.",
    url: "https://www.aap.org/immunization",
    category: "Pediatrics",
    language: "English",
    source: "American Academy of Pediatrics",
  },
  {
    objectID: "sys-006",
    title: "Heel Pain and Sever's Disease",
    description: "Information about heel pain in growing children and adolescents.",
    url: "https://www.aap.org/severs-disease",
    category: "Pediatrics",
    language: "English",
    source: "American Academy of Pediatrics",
  },
  {
    objectID: "sys-007",
    title: "Prenatal Care Guidelines",
    description: "Essential information for expecting mothers about prenatal visits and healthy pregnancy.",
    url: "https://www.acog.org/prenatal-care",
    category: "OB/GYN",
    language: "English",
    source: "American College of Obstetricians and Gynecologists",
  },
  {
    objectID: "sys-008",
    title: "Breastfeeding Your Baby",
    description: "Tips and guidance for successful breastfeeding.",
    url: "https://www.aap.org/breastfeeding",
    category: "Pediatrics",
    language: "English",
    source: "American Academy of Pediatrics",
  },
  {
    objectID: "sys-009",
    title: "Asthma-Friendly Schools Initiative",
    description: "Resources for managing asthma in school settings.",
    url: "https://www.lung.org/asthma-schools",
    category: "Respiratory",
    language: "English",
    source: "American Lung Association",
  },
  {
    objectID: "sys-010",
    title: "A Helping Hand: Resource Guide for People with Cancer",
    description: "Support resources and coping strategies for cancer patients and families.",
    url: "https://www.cancer.org/helping-hand",
    category: "Cancer Care",
    language: "English",
    source: "Cancer Care",
  },
  {
    objectID: "sys-011",
    title: "Understanding Cholesterol",
    description: "What cholesterol is, how it affects your health, and steps to manage it.",
    url: "https://www.heart.org/cholesterol",
    category: "Heart Health",
    language: "English",
    source: "American Heart Association",
  },
  {
    objectID: "sys-012",
    title: "Newborn Care Basics",
    description: "Everything new parents need to know about caring for their newborn.",
    url: "https://www.aap.org/newborn-care",
    category: "Pediatrics",
    language: "English",
    source: "American Academy of Pediatrics",
  },
  {
    objectID: "sys-013",
    title: "Depression: What You Need to Know",
    description: "Recognizing symptoms of depression and finding help.",
    url: "https://www.nimh.nih.gov/depression",
    category: "Mental Health",
    language: "English",
    source: "National Institute of Mental Health",
  },
  {
    objectID: "sys-014",
    title: "Managing Arthritis Pain",
    description: "Strategies for coping with arthritis including exercise, medication, and lifestyle changes.",
    url: "https://www.arthritis.org/managing-pain",
    category: "Orthopedics",
    language: "English",
    source: "Arthritis Foundation",
  },
  {
    objectID: "sys-015",
    title: "Flu Prevention and Treatment",
    description: "How to protect yourself from the flu and what to do if you get sick.",
    url: "https://www.cdc.gov/flu",
    category: "General Health",
    language: "English",
    source: "Centers for Disease Control and Prevention",
  },
  {
    objectID: "sys-016",
    title: "Healthy Sleep Habits",
    description: "Tips for improving sleep quality and establishing healthy sleep routines.",
    url: "https://www.sleepfoundation.org/healthy-sleep",
    category: "General Health",
    language: "English",
    source: "National Sleep Foundation",
  },
  {
    objectID: "sys-017",
    title: "Stroke Warning Signs",
    description: "Learn to recognize the signs of stroke and when to call 911.",
    url: "https://www.stroke.org/warning-signs",
    category: "Heart Health",
    language: "English",
    source: "American Stroke Association",
  },
  {
    objectID: "sys-018",
    title: "Skin Cancer Prevention",
    description: "How to protect your skin from sun damage and reduce cancer risk.",
    url: "https://www.aad.org/skin-cancer-prevention",
    category: "Dermatology",
    language: "English",
    source: "American Academy of Dermatology",
  },
  {
    objectID: "sys-019",
    title: "Cómo manejar la diabetes tipo 2",
    description: "Guía completa para el manejo de la diabetes tipo 2.",
    url: "https://www.cdc.gov/diabetes/spanish",
    category: "Diabetes",
    language: "Spanish",
    source: "Centers for Disease Control and Prevention",
  },
  {
    objectID: "sys-020",
    title: "Physical Therapy After Knee Replacement",
    description: "Exercise and recovery guidelines following total knee replacement surgery.",
    url: "https://www.aaos.org/knee-replacement-pt",
    category: "Orthopedics",
    language: "English",
    source: "American Academy of Orthopaedic Surgeons",
  },
];
